[package]
name = "graph_lib"
version = "0.1.0"
authors = ["Dario Gonzalez <goiradio1@gmail.com>"]
edition = "2018"

[dependencies]
permutohedron = "*"
rayon = "1.1"
base64 = "*"
bitvec = "0.14"
indicatif = "*"

[features]
default = ["bv_graph"]
vec_graph = []
bv_graph = []